/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GRV7zw9VXIX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import moment from 'moment';

// src/types/flight.ts
export interface FlightData {
  departure_iataCode: any;
  arrival_iataCode: any;
  departure_dateTime: any;
  arrival_dateTime: any;
  carrierCode: any;
  price: any;
}

interface FlightsProps {
  data: FlightData[];
}

export function Flights({data}:FlightsProps) {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Flight Options</CardTitle>
      </CardHeader>
      <CardContent className="max-h-[400px] overflow-y-auto">
        <div className="grid gap-4">

          {
            data.map((flight, index) => (
              <div key={index} className="grid grid-cols-[1fr_auto] items-center gap-4 p-4 rounded-md bg-muted">
                <div className="grid gap-1">
                  <div className="flex items-center gap-2">
                    <div className="text-2xl font-medium">{flight.departure_iataCode}</div>
                    <ArrowRightIcon className="w-4 h-4 text-muted-foreground" />
                    <div className="text-2xl font-medium">{flight.arrival_iataCode}</div>
                  </div>
                  <div className="flex items-center gap-2 text-muted-foreground">
                    <ClockIcon className="w-4 h-4" />
                    <div>{moment(flight.departure_dateTime).format('hh:MM A')} - {moment(flight.arrival_dateTime).format('hh:MM A')}</div>
                  </div>
                  <div className="flex items-center gap-2 text-muted-foreground">
                    <PlaneIcon className="w-4 h-4" />
                    <div>{flight.carrierCode}</div>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-medium">${flight.price}</div>
                </div>
              </div>
            ))
          }

        </div>
      </CardContent>
    </Card>
  )
}

function ArrowRightIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function ClockIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function PlaneIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  )
}
