/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xdTvkiSRgoo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Loading() {
  return (
    <div className="flex items-center justify-center bg-muted/50 rounded-md p-2 dark:bg-muted/75">
      <div className="relative w-8 h-8 animate-spin rounded-full bg-gradient-to-r from-primary to-primary-foreground">
        <div className="absolute inset-0.5 rounded-full bg-muted dark:bg-muted" />
      </div>
    </div>
  )
}
