/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qI1T1g1Q63J
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardContent } from "@/components/ui/card"

export function Weather({props}:any) {
  const { city, temperature, weatherCondition, windSpeed, humidity } = props
  return (
    <Card className="w-full max-w-md">
      <CardHeader className="bg-muted/20 p-6">
        <div className="flex items-center gap-4">
          <div className="grid gap-1">
            <h2 className="text-2xl font-bold"></h2>
            <p className="text-muted-foreground">Weather Summary</p>
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-6 grid gap-4">
        <div className="flex items-center gap-4">
          <div className="bg-muted rounded-md flex items-center justify-center aspect-square w-12">
            <SunIcon className="w-6 h-6" />
          </div>
          <div className="grid gap-1">
            <div className="text-4xl font-bold">{props.temperature_2m}°F</div>
            <div className="text-muted-foreground">{props.condition}</div>
          </div>
        </div>
        <hr />
        <div className="grid sm:grid-cols-2 gap-4">
          <div className="flex items-center gap-4">
            <div className="bg-muted rounded-md flex items-center justify-center aspect-square w-10">
              <WindIcon className="w-5 h-5" />
            </div>
            <div className="grid gap-1">
              <div className="font-medium">Wind</div>
              <div className="text-muted-foreground">{props.wind_speed_10m || 'NA'}mph</div>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="bg-muted rounded-md flex items-center justify-center aspect-square w-10">
              <DropletIcon className="w-5 h-5" />
            </div>
            <div className="grid gap-1">
              <div className="font-medium">Humidity</div>
              <div className="text-muted-foreground">{props.relative_humidity_2m}%</div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

function DropletIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z" />
    </svg>
  )
}


function SunIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}


function WindIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 0 14 16H2" />
    </svg>
  )
}
